### ISSUE TITLE
Datasets for developing

### ISSUE THREAD

**Issue by malmans2** [pyNEMO/pyDOMCFG#6]
Maybe we should start with adding a module to generate small and simple [xarray Datasets](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.html) with all the input variables we need to get started (e.g., the equivalent of NEMO coordinates/bathymetry files). 

Say we are developing/testing/benchmarking a new function, we can just do something like:
```python
from pydomcfg.datasets import flat_bathy_ds

def create_domain_cfg(ds: Dataset, ...):
    ...
    return domain_cfg_ds

create_domain_cfg(flat_bathy_ds)
```

The real case scenario would become something like:
```python
import pydomcfg
import xarray as xr

ds = xr.open_dataset("bathymetry_orca1.nc")
domain_cfg_ds = pydomcfg.create_domain_cfg(ds)
domain_cfg_ds.to_netcdf("domain_cfg_orca1.nc")
```

This way everything we need to develop is self-contained and we don't have to use/share files with data.

**Comment by oceandie** [comment]
Cool, like the idea!

**Comment by oceandie** [comment]
If I understand correctly your code, you give in input e1 and e2 (in m?) and from there you compute the coordinates assuming that the first coordinate is 0. While I see how this could be useful for regular regional domain using cartesian coordinates (if thay are in m), I think it could be quite limited for domains (both regional or global) using regular geographical horizontal grids. Maybe we can use the more general classical approach where you give in input the min and max lon and lat of your domain and the number of grid points you want to use and then e1{t,u,v,f} and e2{t,u,v,f} are computed approximating derivatives with finite differences. What do you think? ... I already have some code for this in case ...

**Comment by malmans2** [comment]
Yes, I don't have code ready for the spherical coordinates case, so I didn't cover it as it needs a bit of thought.
Does it make any difference cartesian vs spherical for the vertical coordinates task?

Either way, it would be good to make it more general!
I've been only cutting out regional domains from ORCA so far, so I'd find it quite helpful.
