### ISSUE TITLE
pyDOMCFG code structure

### ISSUE THREAD

**Issue by oceandie** [pyNEMO/pyDOMCFG#7]
The next step will be to agree the structure of pyDOMCFG code. We agree that I will propose a base structure from which we will start the disussion.

**Comment by jdha** [comment]
Hi @oceandie, I realise that you are going to propose a structure for us to comment on - but while it's in my head I thought I'd jot down a thought...

... as this repo is domcfg should we structure it as, for example, the following? Note this is an example of the high level structure not what files I want to see in it or how the sub packages are to be defined. As we discussed the idea of keeping a similar structure to the fortran I thought perhaps we should at least keep the top level similar e.g. subdirs/subpackage for domzgr, domhgr, dommsk.... obviously were just focusing on domzgr at the moment. I think below these subpackages we can be a little more organic... e.g. with a vert_coords.py that holds all the grid defs (although within that still use the common syntax of s_sf12, s_sh94 etc) and perhaps a libs.py for common code used by more than one of the grid definition functions etc... 

```
pyDOMCFG/
│
│
├── docs/
│   └── pydomcfg
│         ├── domzgr
│         └── domhgr
├── pydomcfg/
│   ├── __init__.py
│   ├── entry_wrapper_script.py
│   ├── domzgr/
│   │   ├── __init__.py
│   │   ├── common.py  (general routines and entry point)
│   │   ├── libs.py (common routines in generating vert coords etc)
│   │   └── vert_coords.py (routines of vert coords e.g. sf12, sh94 etc)
│   │
│   └── domhgr/
│       ├── __init__.py
│       ├── read_write.py
│       └── grids.py
│
├── data/
│   ├── data1
│   └── data2
│
├── tests/
│   ├── domzgr
│   │   ├── test1.py
│   │   └── test2.py
│   │
│   └── domhgr/
│       ├── test1.py
│       └── test2.py
│
├── .gitignore
├── LICENSE
└── README.md
```

**Comment by malmans2** [comment]
Idea about how we could handle parameters.
I think we can make something that looks like NEMO namelists using a class with both `__enter__` and `__exit__`.
This class sets the parameters used by all functions, and users can decide whether to use namelists or not.

Here is an example.
```python
import pydomcfg
# Manually
pydomcfg.set_parameters(ln_s_sh94=True)
# OR, from a reference namelist
pydomcfg.set_parameters.from_namelist("namelist_ref")

# Now we don't have to provide any argument
pydomcfg.create_domain()
# But we can if we want
pydomcfg.create_domain(ln_s_sh94=True)
```

Why `__enter__` and `__exit__`? 
If `__exit__` restores the parameters set when we `__enter__` the class, we can use namelist_cfg like this:
```python
import pydomcfg

# Set reference
pydomcfg.set_parameters.from_namelist("namelist_ref")

# Set namelist_cfg
with pydomcfg.set_parameters.from_namelist("namelist_exp1"):
    pydomcfg.create_domain()

with pydomcfg.set_parameters.from_namelist("namelist_exp2"):
    pydomcfg.create_domain()

# Or manually
with pydomcfg.set_parameters(ln_s_sh94=True):
    pydomcfg.create_domain()

# As we wrapped everything in with statements, at this point reference parameters are set.
```

Then we can add more stuff to this class, like warnings/errors about missing/conflicting parameters, a nice `__repr__`, an option `override: bool` to decide what to do for parameters already set, `error: bool` to raise an error if there are parameters that are not used by `pydomcfg`, ...

**Comment by malmans2** [comment]
Also, `set_parameters` only sets the defaults. We can still override those using functions/methods arguments:
So for example
```python
# This uses SH94
with pydomcfg.set_parameters(ln_s_sh94=True):
    pydomcfg.domzgr.vert_coords() #  Here ln_s_sh94 = ln_s_sf12 = None

# This uses SF12
with pydomcfg.set_parameters(ln_s_sh94=True):
    pydomcfg.domzgr.vert_coords(ln_s_sh94=False, ln_s_sf12=True)
```

All methods/functions arguments should default to `None`. When an argument is `None`, we look at the parameters set by `pydomcfg.set_parameters`

**Comment by malmans2** [comment]
A couple of thoughts about the structure we discussed:

- I think we should place all the public API in a [xarray accessor](http://xarray.pydata.org/en/stable/internals/extending-xarray.html?highlight=accessor#extending-xarray). The accessor is a class that extends xarray (the only argument in init is a Dataset). Users just have to import `pydomcfg`. I think it makes sense to replace `pydomcfg/generate_mesh.py` with `pydomcfg/accessor.py`. For example, assuming that a dataset with coords and bathy already exists:

```python
import pydomcf
ds.domcfg.generate_mesh(*args, **kwargs)
# And maybe additional stuff
ds.domcfg.plot(*args, **kwargs)
ds.domcfg.stats(*args, **kwargs)
```
- I think it makes sense to use [inheritance](https://realpython.com/inheritance-composition-python/). That means that we will have a base class with all methods common to all vertical systems. I think we can replace `pydomcfg/domzgr/gen_mesh.py` with `pydomcfg/domzgr/zgr.py` containing the base class. Then, for example in  `pydomcfg/domzgr/sco.py` the child class would look something like
```python
from .zgr import Zgr
class ZgrSco(Zgr):
```
The accessor basically picks the right `zgr` child class based on the appropriate namelist parameter (e.g., `ln_zco=True`).
I can open a PR just to show the structure I'm thinking it that helps.

**Comment by oceandie** [comment]
> 
> 
> A couple of thoughts about the structure we discussed:
> 
>     * I think we should place all the public API in a [xarray accessor](http://xarray.pydata.org/en/stable/internals/extending-xarray.html?highlight=accessor#extending-xarray). The accessor is a class that extends xarray (the only argument in `__init__` is a Dataset). Users just have to import `pydomcfg`. I think it makes sense to replace `pydomcfg/generate_mesh.py` with `pydomcfg/accessor.py`. For example, assuming that a dataset with coords and bathy already exists:
> 
> 
> ```python
> import pydomcfg
> ds.domcfg.generate_mesh(*args, **kwargs)
> # And maybe additional stuff
> ds.domcfg.plot(*args, **kwargs)
> ds.domcfg.stats(*args, **kwargs)
> ```
> 
>     * I think it makes sense to use [inheritance](https://realpython.com/inheritance-composition-python/). That means that we will have a base class with all methods common to all vertical systems. I think we can replace `pydomcfg/domzgr/gen_mesh.py` with `pydomcfg/domzgr/zgr.py` containing the base class. Then, for example in  `pydomcfg/domzgr/sco.py` the child class would look something like
> 
> 
> ```python
> from .zgr import Zgr
> class ZgrSco(Zgr):
> ```
> 
> The accessor basically picks the right `zgr` child class based on the appropriate namelist parameter (e.g., `ln_zco=True`).
> I can open a PR just to show the structure I'm thinking if that helps.

Yes, maybe with a worked example would help, but I like the idea!

**Comment by malmans2** [comment]
I was trying to put together a PR with a possible structure, but I've the feeling now that it's not the best approach. Maybe it's better to start simple and let the structure evolve step-by-step.

How about we start with a `Zco` class in `domzgr/zco` with just a couple of constraints:
1. The first argument shoud be a dataset, then any parameters used within the class.
```python
class Zco:
    def __init__(self, ds, ...):
        self._ds = ds
```
2. Try to use short methods, separating code that we already know eventually will go in a base class.

When we are done with `Zco` and will move to `Sco` it should be easy to separate common methods and define a base class (`Zgr`).

Same for the xarray accessor, no need to work on it right now. Let's see how the Z coords classes evolve. It seems likely that the accessor will set parameters (e.g., through the context manager discussed above) and will only use a method from the appropriate zgr child class (like `.gen_zgr`).

So I guess our first goal could be:
```python
from pydomcfg.tests.bathymetry import Bathymetry
from pydomcfg.zgr import Zco

# Generate test Bathymetry
ds = Bathymetry(...).flat(...)
# Generate z grid
ds_zgr = Zco(ds, ...).gen_zgr()
```
@oceandie Does that work for you? Do you have everything you need to start working on the `zco` class?

**Comment by oceandie** [comment]
@malmans2 I think so ... I am going to start today to work on it - I'll keep you updated guys

**Comment by oceandie** [comment]
Hi @malmans2  and @jdha ,

I am ready to commit my work on zgr and zco and open a PR.
However, I have a problem with the damn darglint: pre-commit fails in darglint with a very criptic error (below an example for zco module, for zgr module it is similar):

darglint.................................................................Failed
- hook id: darglint
- exit code: 1

pydomcfg/domzgr/zco.py:stretch_zco1:195: DAR002: e (4, 4)
pydomcfg/domzgr/zco.py:stretch_zco2:213: DAR002: e (4, 4)

What do you suggest to do?

BTW, I hate darglint :) :)

**Comment by malmans2** [comment]
Hehehe, open the PR even if it fails, I'll have a look.
If you ran `pre-commit install`, add `--no-verify` to `git commit`: See bottom of https://pydomcfg.readthedocs.io/en/latest/developers/contributing.html#pre-commit-formatting

(we can also just get rid of it if error don't make any sense)
